URL_SERVICE =  "https://4e7aad96-7226-4f22-ba08-0dfb9f7c8a1f.serverhub.tripleten-services.com" #"copia la URL generada sin la  barra inclinada al final"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"